name: flutter_cooker
description: A BLoC pattern code generator for Flutter.
version: 1.0.0
homepage: https://github.com/cylyl/flutter_cooker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_style: #^2.0.3
#   json_to_dart:
#     path: ../json_to_dart
  json_to_dart: ^1.0.5
  path:
  recase:
  mysql1:
  args: ^2.4.2
#  flutter_commons:

dev_dependencies:
  pedantic: ^1.10.0
  analyzer: ^2.0.0
